fn mnt {
  mountpoint mnt >/dev/null >[2=1] && fusermount -q -u mnt >[2]/dev/null
  test -z $"host && host='127.0.0.1:5558'
  9pfuse 127.0.0.1:5558 mnt
}

fn start {
  mnt || exit 1
  cd mnt || exit 1
}

fn assert {
  val=$1 expected=$2 {
    if (test _$"val '!=' _$"expected) {
      echo '!! ERROR: expected '''^$"expected^''' got '''^$"val^'''' >[1=2]
      exit 1
    }
    if not true
  }
}

fn assert_file {
  val=`{cat $1} {
    assert $"val $2
  }
}

fn show {echo ';; '^$1: `{cat $1}}

asserted_fields=(type path background foreground text font)

fn write_fields {
  dir=$1 {
    shift
    while (test $#* -gt 0) {
      key=`{echo $1 | sed 's/^-//'} {
        if (test -n $2) {
          echo $2 >$dir/$key
          if (~ $key $asserted_fields)
            assert_file $dir/$key $2
        }
      }
      shift 2
    }
  }
  true
}

fn add_widget {
  w=$1 dir=$2 {
    mkdir -p $dir
    shift 2
    write_fields $dir -path $w $*
  }
}

fn mk_item {
  dir=$1 {
    mkdir -p $dir
    shift
    write_fields $dir $*
  }
}

fn mk_widget {mk_item $*}
